--SQL COMMANDS 3.2

--QUERY1
--TRACEY SCOTT- ENFORCE REFERENTIAL INTEGRITY ADDING FOREIGN
ALTER TABLE ORDERS
    ADD CONSTRAINT FK_ORDERS_USER
    FOREIGN KEY (USERID) REFERENCES USERBASE (USERID);

--QUERY1B
--TRACEY SCOTT- ENFORCE REFERENTIAL INTEGRITY ADDING FOREIGN
ALTER TABLE ORDERS
    ADD CONSTRAINT FK_ORDERS_PRODUCT
    FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCTLIST (PRODUCTCODE);

--QUERY1C
--TRACEY SCOTT- ENFORCE REFERENTIAL INTEGRITY ADDING FOREIGN
ALTER TABLE REVIEWS
    ADD CONSTRAINT FK_REVIEWS_USER
    FOREIGN KEY (USERID) REFERENCES USERBASE (USERID);

QUERY1D
--TRACEY SCOTT- ENFORCE REFERENTIAL INTEGRITY ADDING FOREIGN
ALTER TABLE USERLIBRARY
ADD CONSTRAINT FK_USERLIBRARY_USER
FOREIGN KEY (USERID) REFERENCES USERBASE (USERID);
--QUERYE
--TRACEY SCOTT- ENFORCE REFERENTIAL INTEGRITY  ADDING FOREIGN
ALTER TABLE USERLIBRARY
ADD CONSTRAINT FK_USERLIBRARY_USERID
FOREIGN KEY (USERID) 
REFERENCES USERBASE (USERID);

--QUERY2
--TRACEY SCOTT- IF YOUR COLUMN IS BIRTHDATE INSTEAD OF DATE OF BIRTH
SELECT
    FIRSTNAME || ' ' || LASTNAME AS FULL_NAME,
    USERNAME
FROM USERBASE
WHERE ADD_MONTHS(REAL_COLUMN_NAME>, 12 * 18 )  <= TRUNC(SYSDATE)
ORDER BY LASTNAME, FIRSTNAME;

--QUERY3
--TRACEY SCOTT- MAX LEGTH AND AVERAGE LEGTH OF USERNAME IN USERBASE
SELECT 
    MAX(LENGTH(USERNAME)) AS MAX_USERNAME_LENGTH, 
    ROUND(AVG(LENGTH(USERNAME)), 2) AS
    AVG_USERNAME_LENGTH
FROM USERBASE;



--QUERY4
--TRACEY SCOTT-DISPLAY QUESTION WITH (WHAT IS OR WAS ) SECURITY QUESTION
SELECT 
    QUESTION 
FROM SECURITYQUESTION
WHERE REGEXP_LIKE(QUESTION, '^(What is|What was)', 'i')
ORDER BY QUESTION;

--QUERY5
--TRACEY SCOTT-FOR EACH PRODUCT IN REVIEWS: PRODUCTCODE, LOWEST RATING, AND REVIEW COUNT.(ORDERBY/DESC)
SELECT 
    PRODUCTCODE, 
    MIN(RATING) AS LOWEST_RATING, 
    COUNT(*) AS REVIEW_COUNT
FROM REVIEWS
GROUP BY PRODUCTCODE
ORDER BY REVIEW_COUNT DESC, PRODUCTCODE;

--QUERY6
--TRACEY SCOTT-FROM WISHLIST: ANY PRODUCTCODE RANKED POSISTION = 1, AND NUMBER OF USERS.    
SELECT
    PRODUCTCODE,
    COUNT(DISTINCT USERID) AS USER_COUNT_AT_POS1
FROM WISHLIST
WHERE POSITION = 1
GROUP BY PRODUCTCODE
ORDER BY USER_COUNT_AT_POS1 DESC, PRODUCTCODE;

--QUERY7
--TRACEY SCOTT-DISPLAY USERID AND TOTAL AMOUNT EACH USER HAS SPENT IN ORDERS 
SELECT 
    USERID, 
    ROUND(SUM(NVL(PRICE, 0)), 2) AS TOTAL_SPENT
FROM ORDERS
GROUP BY USERID
ORDER BY TOTAL_SPENT DESC, USERID;

--QUERY8
--TRACEY SCOTT-GROSS PROFITS OF ALL ORDERS BY PURCHASEDATE, DESCENDIGN BY PROFIT
SELECT 
    TRUNC(PURCHASEDATE)  AS PURCHASE_DAY, 
    ROUND(SUM(NVL(PRICE, 0)), 2) AS GROSS_PROFIT
FROM ORDERS
GROUP BY TRUNC(PURCHASEDATE)
ORDER BY GROSS_PROFIT DESC, PURCHASE_DAY DESC;

--QUERY9
SELECT 
    PRODUCTCODE,
    SUM(NVL(HOURSPLAYED, 0))  AS TOTAL_HOURS
FROM USERLIBRARY
GROUP BY PRODUCTCODE
ORDER BY TOTAL_HOURS DESC, PRODUCTCODE
FETCH FIRST 5 ROWS ONLY;

--QUERY10
--TRACEY SCOTT-Create a view: USERID and count of infractions (highest first).
CREATE OR REPLACE VIEW USER_INFRACTION_COUNTS_V AS
SELECT
    USERID,
    COUNT(*) AS INFRACTION_COUNT
FROM INFRACTIONS
GROUP BY USERID;

QUERY11
--TRACEY SCOTT-Create a view: USERID, RULENUM, and number of times broken (sorted by USERID).
CREATE OR REPLACE VIEW USER_RULE_VIOLATION_COUNTS_V AS
SELECT
    USERID,
    COUNT(*) AS TIMES_BROKEN
FROM INFRACTIONS
GROUP BY USERID, RULENUM;

--QUERY12
--TRACEY SCOTT-reate a view: USERID, RULENUM, and number of times broken (sorted by USERID).
SELECT
    RULENUM,
    PENALTY,
    COUNT(*) AS PENALTY_COUNT
FROM INFRACTIONS
WHERE PENALTY IS NOT NULL
GROUP BY RULENUM, PENALTY
ORDER BY RULENUM, PENALTY_COUNT DESC;

--QUERY13
--TRACEY SCOTT- Time between DATEUPDATED and DATESUBMITTED for CLOSED tickets
SELECT 
    ROUND(AVG(DATEUPDATED - DATESUBMITTED), 4) AS AVG_DAYS, 
    ROUND(MAX(DATEUPDATED - DATESUBMITTED), 4) AS MAX_DAYS, 
    ROUND(MIN(DATEUPDATED - DATESUBMITTED), 4) AS MIN_DAYS, 
    NUMTODSINTERVAL(AVG(DATEUPDATED - DATESUBMITTED), 'DAY') AS AVG_INTERVAL, 
    NUMTODSINTERVAL(MAX(DATEUPDATED - DATESUBMITTED), 'DAY') AS MAX_INTERVAL, 
    NUMTODSINTERVAL(MIN(DATEUPDATED - DATESUBMITTED), 'DAY') AS MIN_INTERVAL 
FROM USERSUPPORT 
WHERE UPPER(STATUS) = 'CLOSED';

--QUERY15
--TRACEY SCOTT- Users whose password contains their first or last name
SELECT 
   USERID,
   FIRSTNAME,
   LASTNAME,
   USERNAME
FROM USERBASE
WHERE INSTR(LOWER(PASSWORD), LOWER(FIRSTNAME)) > 0
   OR INSTR(LOWER(PASSWORD), LOWER(LASTNAME)) > 0
ORDER BY USERID;

--QUERY16
--TRACEY SCOTT- NEW tickets: email, issue, count per date
SELECT 
   PUBLISHER, 
   ROUND(AVG(PRICE), 2) AS AVG_PRICE
FROM PRODUCTLIST
GROUP BY PUBLISHER 
ORDER BY PUBLISHER;  

--QUERY17
--TRACEY SCOTT-View: old products with 25% discount
CREATE OR REPLACE VIEW OLD_PRODUCTS_DISCOUNT_V AS
SELECT 
  PRODUCTNAME,
  ROUND(PRICE * 0.75, 2) AS DISCOUNTED_PRICE
FROM PRODUCTLIST
WHERE RELEASEDATE < ADD_MONTHS(TRUNC(SYSDATE), -60);

    
   --QUERY18
--TRACEY SCOTT-View: old products with 25% discount
SELECT 
    GENRE,
    MAX(PRICE) AS MAX_PRICE,
    MIN(PRICE) AS MIN_PRICE
FROM PRODUCTLIST
GROUP BY GENRE
ORDER BY GENRE;

--QUERY19
--TRACEY SCOTT-View: chatlog for last 7 days
CREATE OR REPLACE VIEW CHATLOG_LAST_WEEK_V AS
SELECT *
FROM CHATLOG
WHERE DATESENT >= (SYSDATE -7)
  AND DATESENT <= SYSDATE;

--QUERY20
--TRACEY SCOTT-View: recent penalties in last month
CREATE OR REPLACE VIEW RECENT_PENALTIES_V AS
SELECT 
    USERID,
    DATEASSIGNED,
    PENALTY
FROM INFRACTIONS
WHERE PENALTY IS NOT NULL
  AND DATEASSIGNED >= ADD_MONTHS(SYSDATE, -1);
    
   
